<?php
/**
 * Predefined referrers.
 *
 * @package ReferrerAnalytics
 */

if ( ! function_exists( 'referrer_analytics_predefined_hosts' ) ) {
	function referrer_analytics_predefined_hosts() {
		return array(
			// Flagged referrers.
			array(
				'host' => 'site.ru',
				'type' => 'bot',
				'name' => 'site.ru',
				'flag' => true,
			),
			array(
				'host'        => 'data.vtcdns.com',
				'type'        => 'referral',
				'name'        => 'data.vtcdns.com',
				'primary_url' => 'http://data.vtcdns.com/',
				'flag'        => true,
			),

			// Google referrers.
			array(
				'host'        => 'google.com',
				'type'        => 'organic',
				'name'        => 'Google',
				'primary_url' => 'https://www.google.com/',
			),
			array(
				'host'        => 'www.google.co.ve',
				'type'        => 'organic',
				'name'        => 'Google (Venezuela)',
				'primary_url' => 'https://www.google.co.ve/',
			),
			array(
				'host'        => 'www.google.at',
				'type'        => 'organic',
				'name'        => 'Google (Austria)',
				'primary_url' => 'https://www.google.at/',
			),
			array(
				'host'        => 'www.google.ca',
				'type'        => 'organic',
				'name'        => 'Google (Canada)',
				'primary_url' => 'https://www.google.ca/',
			),
			array(
				'host'        => 'www.google.com',
				'type'        => 'organic',
				'name'        => 'Google',
				'primary_url' => 'https://www.google.com/',
			),
			array(
				'host'        => 'www.google.cl',
				'type'        => 'organic',
				'name'        => 'Google (Chile)',
				'primary_url' => 'https://www.google.cl/',
			),
			array(
				'host'        => 'www.google.ru',
				'type'        => 'organic',
				'name'        => 'Google (Russia)',
				'primary_url' => 'https://www.google.ru/',
			),
			array(
				'host'        => 'www.google.fr',
				'type'        => 'organic',
				'name'        => 'Google (France)',
				'primary_url' => 'https://www.google.fr/',
			),
			array(
				'host'        => 'www.google.hu',
				'type'        => 'organic',
				'name'        => 'Google (Hungary)',
				'primary_url' => 'https://www.google.hu/',
			),
			array(
				'host'        => 'www.google.in',
				'type'        => 'organic',
				'name'        => 'Google (India)',
				'primary_url' => 'https://www.google.in/',
			),
			array(
				'host'        => 'www.google.it',
				'type'        => 'organic',
				'name'        => 'Google (Italy)',
				'primary_url' => 'https://www.google.it/',
			),
			array(
				'host'        => 'www.google.com.ph',
				'type'        => 'organic',
				'name'        => 'Google (Philippines)',
				'primary_url' => 'https://www.google.com.ph/',
			),
			array(
				'host'        => 'www.google.co.in',
				'type'        => 'organic',
				'name'        => 'Google (India)',
				'primary_url' => 'https://www.google.in/',
			),
			array(
				'host'        => 'www.google.co.uk',
				'type'        => 'organic',
				'name'        => 'Google (United Kingdom)',
				'primary_url' => 'https://www.google.co.uk/',
			),
			array(
				'host'        => 'www.google.ch',
				'type'        => 'organic',
				'name'        => 'Google (Switzerland)',
				'primary_url' => 'https://www.google.ch/',
			),
			array(
				'host'        => 'www.google.co.kr',
				'type'        => 'organic',
				'name'        => 'Google (South Korea)',
				'primary_url' => 'https://www.google.co.kr/',
			),
			array(
				'host'        => 'www.google.co.th',
				'type'        => 'organic',
				'name'        => 'Google (Thailand)',
				'primary_url' => 'https://www.google.co.th/',
			),
			array(
				'host'        => 'www.google.com.eg',
				'type'        => 'organic',
				'name'        => 'Google (Egypt)',
				'primary_url' => 'https://www.google.com.eg/',
			),
			array(
				'host'        => 'www.google.com.ar',
				'type'        => 'organic',
				'name'        => 'Google (Argentina)',
				'primary_url' => 'https://www.google.com.ar/',
			),
			array(
				'host'        => 'www.google.com.br',
				'type'        => 'organic',
				'name'        => 'Google (Brazil)',
				'primary_url' => 'https://www.google.com.br/',
			),
			array(
				'host'        => 'www.google.ro',
				'type'        => 'organic',
				'name'        => 'Google (Romania)',
				'primary_url' => 'https://www.google.ro/',
			),
			array(
				'host'        => 'www.google.com.au',
				'type'        => 'organic',
				'name'        => 'Google (Australia)',
				'primary_url' => 'https://www.google.com.au/',
			),
			array(
				'host'        => 'www.google.dk',
				'type'        => 'organic',
				'name'        => 'Google (Denmark)',
				'primary_url' => 'https://www.google.dk/',
			),
			array(
				'host'        => 'www.google.de',
				'type'        => 'organic',
				'name'        => 'Google (Germany)',
				'primary_url' => 'https://www.google.de/',
			),
			array(
				'host'        => 'www.google.pl',
				'type'        => 'organic',
				'name'        => 'Google (Poland)',
				'primary_url' => 'https://www.google.pl/',
			),
			array(
				'host'        => 'www.google.com.tr',
				'type'        => 'organic',
				'name'        => 'Google (Turkey)',
				'primary_url' => 'https://www.google.com.tr/',
			),
			array(
				'host'        => 'www.google.com.tw',
				'type'        => 'organic',
				'name'        => 'Google (Taiwan)',
				'primary_url' => 'https://www.google.com.tw/',
			),
			array(
				'host'        => 'www.google.com.vn',
				'type'        => 'organic',
				'name'        => 'Google (Vietnam)',
				'primary_url' => 'https://www.google.com.vn/',
			),
			array(
				'host'        => 'www.google.hn',
				'type'        => 'organic',
				'name'        => 'Google (Honduras)',
				'primary_url' => 'https://www.google.hn/',
			),
			array(
				'host'        => 'www.google.com.sg',
				'type'        => 'organic',
				'name'        => 'Google (Singapore)',
				'primary_url' => 'https://www.google.com.sg/',
			),
			array(
				'host'        => 'www.google.com.hk',
				'type'        => 'organic',
				'name'        => 'Google (Hong Kong)',
				'primary_url' => 'https://www.google.com.hk/',
			),
			array(
				'host'        => 'www.google.com.mx',
				'type'        => 'organic',
				'name'        => 'Google (Mexico)',
				'primary_url' => 'https://www.google.com.mx/',
			),
			array(
				'host'        => 'support.google.com',
				'type'        => 'organic',
				'name'        => 'Google Support',
				'primary_url' => 'https://support.google.com/',
			),
			array(
				'host'        => 'cse.google.com',
				'type'        => 'organic',
				'name'        => 'Google (Creator Search)',
				'primary_url' => 'https://cse.google.com/',
			),
			array(
				'host'        => 'keep.google.com',
				'type'        => 'organic',
				'name'        => 'Google Keep',
				'primary_url' => 'https://keep.google.com/u/0/',
			),
			array(
				'host'        => 'www.google.co.id',
				'type'        => 'organic',
				'name'        => 'Google (Indonesia)',
				'primary_url' => 'https://www.google.co.id/',
			),
			array(
				'host'        => 'www.google.cm',
				'type'        => 'organic',
				'name'        => 'Google (Cameroon)',
				'primary_url' => 'https://www.google.cm/',
			),
			array(
				'host'        => 'www.google.co.il',
				'type'        => 'organic',
				'name'        => 'Google (Israel)',
				'primary_url' => 'https://www.google.co.il/',
			),
			array(
				'host'        => 'search.google.com',
				'type'        => 'organic',
				'name'        => 'Google',
				'primary_url' => 'https://www.google.com/',
			),
			array(
				'host'        => 'www.google.cz',
				'type'        => 'organic',
				'name'        => 'Google (Czechia)',
				'primary_url' => 'https://www.google.cz/',
			),
			array(
				'host'        => 'www.google.co.jp',
				'type'        => 'organic',
				'name'        => 'Google (Japan)',
				'primary_url' => 'https://www.google.co.jp/',
			),
			array(
				'host'        => 'www.google.pt',
				'type'        => 'organic',
				'name'        => 'Google (Portugal)',
				'primary_url' => 'https://www.google.com.co/',
			),
			array(
				'host'        => 'www.google.com.co',
				'type'        => 'organic',
				'name'        => 'Google (Colombia)',
				'primary_url' => 'https://www.google.pt/',
			),
			array(
				'host'        => 'www.google.ae',
				'type'        => 'organic',
				'name'        => 'Google (United Arab Emirates)',
				'primary_url' => 'https://www.google.ae/',
			),
			array(
				'host'        => 'www.google.com.ua',
				'type'        => 'organic',
				'name'        => 'Google (Ukraine)',
				'primary_url' => 'https://www.google.com.ua/',
			),
			array(
				'host'        => 'www.google.co.za',
				'type'        => 'organic',
				'name'        => 'Google (South Africa)',
				'primary_url' => 'https://www.google.co.za/',
			),
			array(
				'host'        => 'www.google.nl',
				'type'        => 'organic',
				'name'        => 'Google (Netherlands)',
				'primary_url' => 'https://www.google.nl/',
			),
			array(
				'host'        => 'www.google.fi',
				'type'        => 'organic',
				'name'        => 'Google (Finland)',
				'primary_url' => 'https://www.google.fi/',
			),
			array(
				'host'        => 'www.google.kz',
				'type'        => 'organic',
				'name'        => 'Google (Kazakhstan)',
				'primary_url' => 'https://www.google.kz/',
			),
			array(
				'host'        => 'www.google.com.my',
				'type'        => 'organic',
				'name'        => 'Google (Malaysia)',
				'primary_url' => 'https://www.google.com.my/',
			),
			array(
				'host'        => 'www.google.se',
				'type'        => 'organic',
				'name'        => 'Google (Sweden)',
				'primary_url' => 'https://www.google.se/',
			),
			array(
				'host'        => 'www.google.es',
				'type'        => 'organic',
				'name'        => 'Google (Spain)',
				'primary_url' => 'https://www.google.es/',
			),
			array(
				'host'        => 'www.google.no',
				'type'        => 'organic',
				'name'        => 'Google (Norway)',
				'primary_url' => 'https://www.google.no/',
			),
			array(
				'host'        => 'mail.google.com',
				'type'        => 'email',
				'name'        => 'Gmail',
				'primary_url' => 'https://mail.google.com/',
			),
			array(
				'host'        => 'cloud.google.com',
				'type'        => 'referral',
				'name'        => 'Gmail',
				'primary_url' => 'https://cloud.google.com/',
			),
			array(
				'host'        => 'webcache.googleusercontent.com',
				'type'        => 'referral',
				'name'        => 'Google (cache)',
				'primary_url' => 'https://www.google.com/',
			),
			array(
				'host'        => 'www.google.com.cu',
				'type'        => 'organic',
				'name'        => 'Google (Cuba)',
				'primary_url' => 'https://www.google.com.cu/',
			),
			array(
				'host'        => 'www.google.be',
				'type'        => 'organic',
				'name'        => 'Google (Belgium)',
				'primary_url' => 'https://www.google.be/',
			),
			array(
				'host'        => 'www.google.sk',
				'type'        => 'organic',
				'name'        => 'Google (Slovakia)',
				'primary_url' => 'https://www.google.sk/',
			),
			array(
				'host'        => 'www.google.com.sl',
				'type'        => 'organic',
				'name'        => 'Google (Sierra Leone)',
				'primary_url' => 'https://www.google.com.sl/',
			),
			array(
				'host'        => 'www.google.gr',
				'type'        => 'organic',
				'name'        => 'Google (Greece)',
				'primary_url' => 'https://www.google.gr/',
			),
			array(
				'host'        => 'www.google.rs',
				'type'        => 'organic',
				'name'        => 'Google (Serbia)',
				'primary_url' => 'https://www.google.rs/',
			),
			array(
				'host'        => 'www.google.bj',
				'type'        => 'organic',
				'name'        => 'Google (Benin)',
				'primary_url' => 'https://www.google.bj/',
			),
			array(
				'host'        => 'www.google.com.np',
				'type'        => 'organic',
				'name'        => 'Google (Nepal)',
				'primary_url' => 'https://www.google.com.np/',
			),
			array(
				'host'        => 'www.google.hr',
				'type'        => 'organic',
				'name'        => 'Google (Croatia)',
				'primary_url' => 'https://www.google.hr/',
			),
			array(
				'host'        => 'www.google.is',
				'type'        => 'organic',
				'name'        => 'Google (Iceland)',
				'primary_url' => 'https://www.google.is/',
			),
			array(
				'host'        => 'www.google.com.pk',
				'type'        => 'organic',
				'name'        => 'Google (Pakistan)',
				'primary_url' => 'https://www.google.com.pk/',
			),
			array(
				'host'        => 'www.google.az',
				'type'        => 'organic',
				'name'        => 'Google (Azerbaijan)',
				'primary_url' => 'https://www.google.az/',
			),
			array(
				'host'        => 'www.google.ie',
				'type'        => 'organic',
				'name'        => 'Google (Ireland)',
				'primary_url' => 'https://www.google.ie/',
			),
			array(
				'host'        => 'optimize.google.com',
				'type'        => 'referral',
				'name'        => 'Google Optimize',
				'primary_url' => 'https://optimize.google.com/',
			),
			array(
				'host'        => 'com.google.android.gm',
				'type'        => 'email',
				'name'        => 'Gmail (android)',
				'primary_url' => 'https://mail.google.com/',
			),
			array(
				'host'        => 'com.google.android.googlequicksearchbox',
				'type'        => 'organic',
				'name'        => 'Google (android)',
				'primary_url' => 'https://google.com',
			),
			array(
				'host'        => 'translate.googleusercontent.com',
				'type'        => 'organic',
				'name'        => 'Google Translate',
				'primary_url' => 'https://translate.google.com/',
			),

      // Bing referrers.
			array(
				'host'        => 'www.bing.com',
				'type'        => 'organic',
				'name'        => 'Bing',
				'primary_url' => 'https://www.bing.com/',
			),
			array(
				'host'        => 'cn.bing.com',
				'type'        => 'organic',
				'name'        => 'Bing (China)',
				'primary_url' => 'https://www.bing.com/?mkt=zh-CN',
			),
			array(
				'host'        => 'www4.bing.com',
				'type'        => 'organic',
				'name'        => 'Bing',
				'primary_url' => 'https://www4.bing.com/',
			),

			// Yahoo referrers.
			array(
				'host'        => 'yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo',
				'primary_url' => 'https://www.yahoo.com/',
			),
			array(
				'host'        => 'r.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo',
				'primary_url' => 'https://www.yahoo.com/',
			),
			array(
				'host'        => 'search.yahoo.co.jp',
				'type'        => 'organic',
				'name'        => 'Yahoo (Japan)',
				'primary_url' => 'https://search.yahoo.co.jp/',
			),
			array(
				'host'        => 'search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo',
				'primary_url' => 'https://www.yahoo.com/',
			),
			array(
				'host'        => 'fr.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (France)',
				'primary_url' => 'https://fr.search.yahoo.com/',
			),
			array(
				'host'        => 'uk.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (United Kingdom)',
				'primary_url' => 'https://uk.search.yahoo.com/',
			),
			array(
				'host'        => 'hk.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (Hong Kong)',
				'primary_url' => 'https://hk.search.yahoo.com/',
			),
			array(
				'host'        => 'us.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo',
				'primary_url' => 'https://us.search.yahoo.com/',
			),
			array(
				'host'        => 'in.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (India)',
				'primary_url' => 'https://in.search.yahoo.com/',
			),
			array(
				'host'        => 'tw.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (Taiwan)',
				'primary_url' => 'https://tw.search.yahoo.com/',
			),
			array(
				'host'        => 'au.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (Australia)',
				'primary_url' => 'https://search.yahoo.com/',
			),
			array(
				'host'        => 'pl.search.yahoo.com',
				'type'        => 'organic',
				'name'        => 'Yahoo (Poland)',
				'primary_url' => 'https://pl.search.yahoo.com/',
			),
			array(
				'host'        => 'finance.yahoo.com',
				'type'        => 'referral',
				'name'        => 'Yahoo Finance',
				'primary_url' => 'https://finance.yahoo.com/',
			),
			array(
				'host'        => 'mail.yahoo.com',
				'type'        => 'email',
				'name'        => 'Yahoo',
				'primary_url' => 'https://login.yahoo.com/',
			),

      // Other search engines referrers.
			array(
				'host'        => 'duckduckgo.com',
				'type'        => 'organic',
				'name'        => 'DuckDuckGo',
				'primary_url' => 'https://duckduckgo.com/',
			),
			array(
				'host'        => 'html.duckduckgo.com',
				'type'        => 'organic',
				'name'        => 'DuckDuckGo',
				'primary_url' => 'https://duckduckgo.com/',
			),
			array(
				'host'        => 'm.baidu.com',
				'type'        => 'organic',
				'name'        => 'Baidu (mobile)',
				'primary_url' => 'http://m.baidu.com/',
			),
			array(
				'host'        => 'baidu.com',
				'type'        => 'organic',
				'name'        => 'Baidu',
				'primary_url' => 'http://www.baidu.com/',
			),
			array(
				'host'        => 'www.baidu.com',
				'type'        => 'organic',
				'name'        => 'Baidu',
				'primary_url' => 'http://www.baidu.com/',
			),
			array(
				'host'        => 'www.ecosia.org',
				'type'        => 'organic',
				'name'        => 'Ecosia',
				'primary_url' => 'https://www.ecosia.org/',
			),
			array(
				'host'        => 'www.qwant.com',
				'type'        => 'organic',
				'name'        => 'Qwant',
				'primary_url' => 'https://www.qwant.com/',
			),
			array(
				'host'        => 'go.mail.ru',
				'type'        => 'organic',
				'name'        => 'Поиск Mail.Ru',
				'primary_url' => 'https://go.mail.ru/',
			),
			array(
				'host'        => 'search.aol.com',
				'type'        => 'organic',
				'name'        => 'AOL',
				'primary_url' => 'https://search.aol.com/',
			),
			array(
				'host'        => 'www.besthelp.com',
				'type'        => 'organic',
				'name'        => 'BestHelp',
				'primary_url' => 'https://www.besthelp.com/',
			),
			array(
				'host'        => 'yandex.com',
				'type'        => 'organic',
				'name'        => 'Yandex',
				'primary_url' => 'https://yandex.com/',
			),
			array(
				'host'        => 'www.yandex.kz',
				'type'        => 'organic',
				'name'        => 'Yandex (Kazakhstan)',
				'primary_url' => 'https://yandex.kz/',
			),
			array(
				'host'        => 'm.instasrch.com',
				'type'        => 'organic',
				'name'        => 'Instasrch (mobile)',
				'primary_url' => 'https://m.instasrch.com/search',
			),

      // Social media referrers.
			array(
				'host'        => 't.co',
				'type'        => 'social',
				'name'        => 'Twitter',
				'primary_url' => 'https://twitter.com/',
			),
			array(
				'host'        => 'twitter.com',
				'type'        => 'social',
				'name'        => 'Twitter',
				'primary_url' => 'https://twitter.com/',
			),
			array(
				'host'        => 'www.twitter.com',
				'type'        => 'social',
				'name'        => 'Twitter',
				'primary_url' => 'https://twitter.com/',
			),
			array(
				'host'        => 'www.facebook.com',
				'type'        => 'social',
				'name'        => 'Facebook',
				'primary_url' => 'https://www.facebook.com/',
			),
			array(
				'host'        => 'm.facebook.com',
				'type'        => 'social',
				'name'        => 'Facebook (mobile)',
				'primary_url' => 'https://www.facebook.com/',
			),
			array(
				'host'        => 'l.facebook.com',
				'type'        => 'social',
				'name'        => 'Facebook',
				'primary_url' => 'https://www.facebook.com/',
			),
			array(
				'host'        => 'www.linkedin.com',
				'type'        => 'social',
				'name'        => 'LinkedIn',
				'primary_url' => 'https://www.linkedin.com/',
			),
			array(
				'host'        => 'www.linkedin.cn',
				'type'        => 'social',
				'name'        => 'LinkedIn (China)',
				'primary_url' => 'http://www.linkedin.cn/',
			),
			array(
				'host'        => 'www.instagram.com',
				'type'        => 'social',
				'name'        => 'Instagram',
				'primary_url' => 'https://www.instagram.com/',
			),
			array(
				'host'        => 'www.youtube.com',
				'type'        => 'social',
				'name'        => 'YouTube',
				'primary_url' => 'https://www.youtube.com/',
			),
			array(
				'host'        => 'www.reddit.com',
				'type'        => 'social',
				'name'        => 'reddit',
				'primary_url' => 'https://www.reddit.com/',
			),
			array(
				'host'        => 'l.messenger.com',
				'type'        => 'social',
				'name'        => 'Facebook (Messenger)',
				'primary_url' => 'https://www.messenger.com/',
			),
			array(
				'host'        => 'com.linkedin.android',
				'type'        => 'social',
				'name'        => 'LinkedIn (Android)',
				'primary_url' => 'https://www.linkedin.com/',
			),
			array(
				'host'        => 't.umblr.com',
				'type'        => 'social',
				'name'        => 'Tumblr',
				'primary_url' => 'https://www.tumblr.com/',
			),
			array(
				'host'        => 'lnkd.in',
				'type'        => 'social',
				'name'        => 'LinkedIn',
				'primary_url' => 'https://www.linkedin.com/',
			),

      // WordPress referrers.
			array(
				'host'        => 'wordpress.org',
				'type'        => 'referral',
				'name'        => 'WordPress',
				'primary_url' => 'https://wordpress.org/',
			),
			array(
				'host'        => 'fr.wordpress.org',
				'type'        => 'referral',
				'name'        => 'WordPress (France)',
				'primary_url' => 'https://fr.wordpress.org/',
			),
			array(
				'host'        => 'nl.wordpress.org',
				'type'        => 'referral',
				'name'        => 'WordPress (Netherlands)',
				'primary_url' => 'https://nl.wordpress.org/',
			),
			array(
				'host'        => 'es.wordpress.org',
				'type'        => 'referral',
				'name'        => 'WordPress (Spain)',
				'primary_url' => 'https://es.wordpress.org/',
			),
			array(
				'host'        => 'nb.wordpress.org',
				'type'        => 'referral',
				'name'        => 'WordPress (Norway)',
				'primary_url' => 'https://nb.wordpress.org/',
			),

			// Other referrers.
			array(
				'host'        => 'play.vidyard.com',
				'type'        => 'referral',
				'name'        => 'Vidyard',
				'primary_url' => 'https://www.vidyard.com/',
			),
			array(
				'host'        => 'share.vidyard.com',
				'type'        => 'referral',
				'name'        => 'Vidyard',
				'primary_url' => 'https://www.vidyard.com/',
			),
			array(
				'host'        => 'tester.test.io',
				'type'        => 'referral',
				'name'        => 'test IO (Tester)',
				'primary_url' => 'https://tester.test.io/sign_in',
			),
			array(
				'host'        => 'pubs.spe.org',
				'type'        => 'referral',
				'name'        => 'Society of Petroleum Engineers',
				'primary_url' => 'https://pubs.spe.org/en/',
			),
			array(
				'host'        => 'hubs.mozilla.com',
				'type'        => 'referral',
				'name'        => 'Hubs',
				'primary_url' => 'https://hubs.mozilla.com/',
			),
			array(
				'host'        => 'css-tricks.com',
				'type'        => 'referral',
				'name'        => 'CSS-Tricks',
				'primary_url' => 'https://css-tricks.com/',
			),
			array(
				'host'        => 'lurkmore.to',
				'type'        => 'referral',
				'name'        => 'Lurkmore',
				'primary_url' => 'https://lurkmore.to/',
			),
			array(
				'host'        => 'drupalsun.com',
				'type'        => 'referral',
				'name'        => 'Drupal Sun',
				'primary_url' => 'https://drupalsun.com/',
			),
			array(
				'host'        => 'cdpn.io',
				'type'        => 'referral',
				'name'        => 'CodePen',
				'primary_url' => 'https://codepen.io/',
			),
			array(
				'host'        => 'amzn.to',
				'type'        => 'referral',
				'name'        => 'Amazon',
				'primary_url' => 'https://www.amazon.com/',
			),
			array(
				'host'        => 'jobsnearme.online',
				'type'        => 'referral',
				'name'        => 'Jobs Near Me',
				'primary_url' => 'https://jobsnearme.online/',
			),
			array(
				'host'        => 'www.entermedia.com',
				'type'        => 'referral',
				'name'        => 'Entermedia, LLC.',
				'primary_url' => 'https://www.entermedia.com/',
			),
			array(
				'host'        => 'entermedianow.com',
				'type'        => 'referral',
				'name'        => 'Entermedia, LLC.',
				'primary_url' => 'https://www.entermedia.com/',
			),
			array(
				'host'        => 'www.entermedianow.com',
				'type'        => 'referral',
				'name'        => 'Entermedia, LLC.',
				'primary_url' => 'https://www.entermedia.com/',
			),
			array(
				'host'        => 'entermedia.com',
				'type'        => 'referral',
				'name'        => 'Entermedia, LLC.',
				'primary_url' => 'https://www.entermedia.com/',
			),
			array(
				'host'        => 'www.entermedia.com',
				'type'        => 'referral',
				'name'        => 'Entermedia, LLC.',
				'primary_url' => 'https://www.entermedia.com/',
			),
			array(
				'host'        => 'forum.bubble.io',
				'type'        => 'referral',
				'name'        => 'Bubble Forum',
				'primary_url' => 'https://forum.bubble.io/'
				),
			array(
				'host'        => 'www.benmarshall.me',
				'type'        => 'referral',
				'name'        => 'Ben Marshall',
				'primary_url' => 'https://benmarshall.me',
			),
			array(
				'host'        => 'benmarshall.me',
				'type'        => 'referral',
				'name'        => 'Ben Marshall',
				'primary_url' => 'https://benmarshall.me',
			),
			array(
				'host'        => '35.209.238.75',
				'type'        => 'referral',
				'name'        => 'Ben Marshall',
				'primary_url' => 'https://benmarshall.me',
			),
			array(
				'host'        => 'github.com',
				'type'        => 'referral',
				'name'        => 'GitHub',
				'primary_url' => 'https://github.com/',
			),
			array(
				'host'        => 'school.nextacademy.com',
				'type'        => 'referral',
				'name'        => 'NEXT Academy',
				'primary_url' => 'https://school.nextacademy.com/',
			),
			array(
				'host'        => 'www.soliddigital.com',
				'type'        => 'referral',
				'name'        => 'Solid Digital',
				'primary_url' => 'https://www.soliddigital.com/',
			),
			array(
				'host'        => 'www.benellile.com',
				'type'        => 'referral',
				'name'        => 'Benlli',
				'primary_url' => 'https://www.benellile.com/',
			),
			array(
				'host'        => 'newsblur.com',
				'type'        => 'referral',
				'name'        => 'NewsBlur',
				'primary_url' => 'https://newsblur.com/',
			),
			array(
				'host'        => 'knowledge.exlibrisgroup.com',
				'type'        => 'referral',
				'name'        => 'Ex Libris Knowledge Center',
				'primary_url' => 'https://knowledge.exlibrisgroup.com/',
			),
			array(
				'host'        => 'anti-crisis-seo.com',
				'type'        => 'bot',
				'name'        => 'SEO Anti-Crisis Tool',
				'primary_url' => 'http://anti-crisis-seo.com',
			),
			array(
				'host'        => 'minepub.net',
				'type'        => 'referral',
				'name'        => 'Minepub',
				'primary_url' => 'https://minepub.net/',
			),
			array(
				'host'        => 'ricoshae.com.au',
				'type'        => 'referral',
				'name'        => 'Ricoshae',
				'primary_url' => 'https://ricoshae.com.au/',
			),
			array(
				'host'        => 'bayriverrealty.com',
				'type'        => 'referral',
				'name'        => 'Bay River Realty',
				'primary_url' => 'http://bayriverrealty.com/',
			),
			array(
				'host'        => 'forums.athemes.com',
				'type'        => 'referral',
				'name'        => 'aThemes Forums',
				'primary_url' => 'https://forums.athemes.com/'
				),
			array(
				'host'        => 'timnath.org',
				'type'        => 'referral',
				'name'        => 'Timnath, CO',
				'primary_url' => 'https://timnath.org/',
			),
			array(
				'host'        => 'spr.com',
				'type'        => 'referral',
				'name'        => 'SPR',
				'primary_url' => 'https://spr.com/',
			),
			array(
				'host'        => 'michaelbox.net',
				'type'        => 'referral',
				'name'        => 'Michael Beckwith',
				'primary_url' => 'https://michaelbox.net/',
			),
			array(
				'host'        => 'forum.zwiicms.com',
				'type'        => 'referral',
				'name'        => 'Support de Zwii',
				'primary_url' => 'http://forum.zwiicms.com/'
				),
			array(
				'host'        => 'wohnparc.de',
				'type'        => 'referral',
				'name'        => 'wohnparc.de',
				'primary_url' => 'https://wohnparc.de/',
			),
			array(
				'host'        => 'scottdeluzio.com',
				'type'        => 'referral',
				'name'        => 'Scott DeLuzio',
				'primary_url' => 'https://scottdeluzio.com/',
			),
			array(
				'host'        => 'theme.co',
				'type'        => 'referral',
				'name'        => 'Theme.co',
				'primary_url' => 'https://theme.co/',
			),
			array(
				'host'        => 'luatduonggia.vn',
				'type'        => 'referral',
				'name'        => 'Công ty Luật Dương Gia',
				'primary_url' => 'https://luatduonggia.vn/',
			),
			array(
				'host'        => 'app.net',
				'type'        => 'referral',
				'name'        => 'App.net',
				'primary_url' => 'https://app.net/',
			),
			array(
				'host'        => 'www.gynecomastia.org',
				'type'        => 'referral',
				'name'        => 'Gynecomastia.org',
				'primary_url' => 'https://www.gynecomastia.org/',
			),
			array(
				'host'        => 'aljlaw.com',
				'type'        => 'referral',
				'name'        => 'The Estate Planning and Elder Law Group',
				'primary_url' => 'http://aljlaw.com/',
			),
			array(
				'host'        => 'rrhelections.com',
				'type'        => 'referral',
				'name'        => 'RRH Elections',
				'primary_url' => 'https://rrhelections.com/',
			),
			array(
				'host'        => 'bit.ly',
				'type'        => 'referral',
				'name'        => 'Bitly',
				'primary_url' => 'https://bitly.com/',
			),
			array(
				'host'        => 'feedly.com',
				'type'        => 'referral',
				'name'        => 'Feedly',
				'primary_url' => 'https://feedly.com/i/welcome',
			),
			array(
				'host'        => 'www.feedly.com',
				'type'        => 'referral',
				'name'        => 'Feedly',
				'primary_url' => 'https://feedly.com/i/welcome',
			),
			array(
				'host'        => '109.199.107.148',
				'type'        => 'referral',
				'name'        => 'SiteGround',
				'primary_url' => 'https://www.siteground.com/',
			),
			array(
				'host'        => 'www.sitepoint.com',
				'type'        => 'referral',
				'name'        => 'SitePoint',
				'primary_url' => 'https://www.sitepoint.com/',
			),
			array(
				'host'        => 'stackoverflow.com',
				'type'        => 'referral',
				'name'        => 'Stack Overflow',
				'primary_url' => 'https://stackoverflow.com/',
			),
			array(
				'host'        => 'generatepress.com',
				'type'        => 'referral',
				'name'        => 'GeneratePress',
				'primary_url' => 'https://generatepress.com/',
			),
			array(
				'host'        => 'www.wpmeta.org',
				'type'        => 'referral',
				'name'        => 'WPMeta',
				'primary_url' => 'http://www.wpmeta.org/',
			),
			array(
				'host'        => 'ask.csdn.net',
				'type'        => 'referral',
				'name'        => '编程技术问答-CSDN问答频道',
				'primary_url' => 'https://ask.csdn.net/',
			),
			array(
				'host'        => 'www.hipwf.com',
				'type'        => 'referral',
				'name'        => 'Heidelberg International Professional Women\'s Forum',
				'primary_url' => 'https://www.hipwf.com/',
			),
			array(
				'host'        => 'www.nanoframework.net',
				'type'        => 'referral',
				'name'        => 'nanoFramework',
				'primary_url' => 'https://www.nanoframework.net/',
			),
			array(
				'host'        => 'stash.trusted.visa.com',
				'type'        => 'bot',
				'name'        => 'stash.trusted.visa.com',
			),
			array(
				'host'        => 'support.advancedcustomfields.com',
				'type'        => 'referral',
				'name'        => 'ACF Support',
				'primary_url' => 'https://support.advancedcustomfields.com/',
			),
			array(
				'host'        => 'austinjeeppeople.com',
				'type'        => 'referral',
				'name'        => 'Austin JeepPeople',
				'primary_url' => 'https://austinjeeppeople.com/',
			),
			array(
				'host'        => 'yandex.ru',
				'type'        => 'organic',
				'name'        => 'Yandex',
				'primary_url' => 'https://yandex.ru/',
			),
			array(
				'host'        => 'confluence.godaddy.com',
				'type'        => 'referral',
				'name'        => 'GoDaddy (Confluence)',
				'primary_url' => 'https://godaddy.okta.com/login/login.htm',
			),
			array(
				'host'        => 'pob.ng',
				'type'        => 'referral',
				'name'        => 'Princesage Online Branding',
				'primary_url' => 'https://pob.ng/',
			),
			array(
				'host'        => 'theabcn.org',
				'type'        => 'referral',
				'name'        => 'American Board of Clinical Neuropsychology',
				'primary_url' => 'https://theabcn.org/',
			),
			array(
				'host'        => 'lenny.pl',
				'type'        => 'referral',
				'name'        => 'Portal Lenny',
				'primary_url' => 'http://lenny.pl/',
			),
			array(
				'host'        => 'www.phase2technology.com',
				'type'        => 'referral',
				'name'        => 'Phase2',
				'primary_url' => 'https://www.phase2technology.com/',
			),
			array(
				'host'        => 'timemachine.ai',
				'type'        => 'referral',
				'name'        => 'Time Machine (SparkCognition)',
				'primary_url' => 'https://timemachine.ai/',
			),
			array(
				'host'        => 'go.sparkcognition.com',
				'type'        => 'referral',
				'name'        => 'SparkCognition',
				'primary_url' => 'https://go.sparkcognition.com/',
			),
			array(
				'host'        => 'sparkcognition.com',
				'type'        => 'referral',
				'name'        => 'SparkCognition',
				'primary_url' => 'https://sparkcognition.com/',
			),
			array(
				'host'        => 'sucuri.net',
				'type'        => 'referral',
				'name'        => 'Sucuri',
				'primary_url' => 'https://sucuri.net/',
			),
			array(
				'host'        => 'www.prnewswire.com',
				'type'        => 'referral',
				'name'        => 'PR Newswire',
				'primary_url' => 'https://www.prnewswire.com/',
			),
			array(
				'host'        => 'iiot-world.com',
				'type'        => 'referral',
				'name'        => 'IIoT World',
				'primary_url' => 'http://iiot-world.com/',
			),
			array(
				'host'        => 'www.yammer.com',
				'type'        => 'referral',
				'name'        => 'Yammer',
				'primary_url' => 'https://www.yammer.com/',
			),
			array(
				'host'        => 'www.g2.com',
				'type'        => 'referral',
				'name'        => 'G2',
				'primary_url' => 'https://www.g2.com/',
			),
			array(
				'host'        => 'www.cognitivetimes.com',
				'type'        => 'referral',
				'name'        => 'Cognitive Times (SparkCognition)',
				'primary_url' => 'https://www.cognitivetimes.com/',
			),
			array(
				'host'        => 'www.gitex.com',
				'type'        => 'referral',
				'name'        => 'GITEX',
				'primary_url' => 'https://www.gitex.com/',
			),
			array(
				'host'        => 'www.jc2ventures.com',
				'type'        => 'referral',
				'name'        => 'JC2 Ventures',
				'primary_url' => 'https://www.jc2ventures.com/',
			),
			array(
				'host'        => 'jukelogic.com',
				'type'        => 'referral',
				'name'        => 'JukeLogic',
				'primary_url' => 'https://jukelogic.com/',
			),
			array(
				'host'        => 'www.av-comparatives.org',
				'type'        => 'referral',
				'name'        => 'AV Comparatives',
				'primary_url' => 'https://www.av-comparatives.org/',
			),
			array(
				'host'        => 'www.scss.tcd.ie',
				'type'        => 'referral',
				'name'        => 'Trinity College Dublin',
				'primary_url' => 'https://www.scss.tcd.ie/',
			),
			array(
				'host'        => 'www.fieldinglawtexas.com',
				'type'        => 'referral',
				'name'        => 'Fielding Law',
				'primary_url' => 'https://www.fieldinglaw.com/',
			),
			array(
				'host'        => 'davidwalsh.name',
				'type'        => 'referral',
				'name'        => 'David Walsh Blog',
				'primary_url' => 'https://davidwalsh.name/',
			),
			array(
				'host'        => 'pi.pardot.com',
				'type'        => 'referral',
				'name'        => 'Pardot',
				'primary_url' => 'https://pi.pardot.com/',
			),
			array(
				'host'        => 'www.nvidia.com',
				'type'        => 'referral',
				'name'        => 'NVIDIA',
				'primary_url' => 'https://www.nvidia.com/',
			),
			array(
				'host'        => 'www.stockwatch.com',
				'type'        => 'referral',
				'name'        => 'Stockwatch',
				'primary_url' => 'https://www.stockwatch.com/',
			),
			array(
				'host'        => 'analyticsindiamag.com',
				'type'        => 'referral',
				'name'        => 'Analytics India Magazine',
				'primary_url' => 'https://analyticsindiamag.com/',
			),
			array(
				'host'        => 'www.theladders.com',
				'type'        => 'referral',
				'name'        => 'Ladders',
				'primary_url' => 'https://www.theladders.com/',
			),
			array(
				'host'        => 'medium.com',
				'type'        => 'referral',
				'name'        => 'Medium',
				'primary_url' => 'https://medium.com/',
			),
			array(
				'host'        => 'emerj.com',
				'type'        => 'referral',
				'name'        => 'Emerj',
				'primary_url' => 'https://emerj.com/',
			),
			array(
				'host'        => 'builtin.com',
				'type'        => 'referral',
				'name'        => 'Built In',
				'primary_url' => 'https://builtin.com/',
			),
			array(
				'host'        => 'brainvueacademy.com',
				'type'        => 'referral',
				'name'        => 'BrainVue Academy',
				'primary_url' => 'https://brainvueacademy.com/',
			),
			array(
				'host'        => 'searchsmart.com.au',
				'type'        => 'referral',
				'name'        => 'Searchsmart',
				'primary_url' => 'https://searchsmart.com.au/',
			),
			array(
				'host'        => 'devfrontend.info',
				'type'        => 'referral',
				'name'        => 'FrontEndDeveloper',
				'primary_url' => 'http://devfrontend.info/',
			),
			array(
				'host'        => 'workona.com',
				'type'        => 'referral',
				'name'        => 'Workona',
				'primary_url' => 'https://workona.com/',
			),
			array(
				'host'        => 'drupal.stackexchange.com',
				'type'        => 'referral',
				'name'        => 'Drupal Answers',
				'primary_url' => 'https://drupal.stackexchange.com/',
			),
			array(
				'host'        => 'refuahhealthcenter.com',
				'type'        => 'referral',
				'name'        => 'Refuah Health Center',
				'primary_url' => 'https://refuahhealth.org/',
			),
			array(
				'host'        => 'www.agencyvista.com',
				'type'        => 'referral',
				'name'        => 'Agency Vista',
				'primary_url' => 'https://agencyvista.com/',
			),
			array(
				'host'        => 'wix.lightning.force.com',
				'type'        => 'referral',
				'name'        => 'Wix.com (Salesforce)',
				'primary_url' => 'https://wix.my.salesforce.com/'
				),
			array(
				'host'        => 'learn.sparkcognition.com',
				'type'        => 'referral',
				'name'        => 'SparkCognition',
				'primary_url' => 'https://www.sparkcognition.com/',
			),
			array(
				'host'        => 'socialmediascanner.eset.com',
				'type'        => 'referral',
				'name'        => 'Social Media Scanner',
				'primary_url' => 'https://socialmediascanner.eset.com/',
			),
			array(
				'host'        => 'preview.pardot.com',
				'type'        => 'referral',
				'name'        => 'Pardot',
				'primary_url' => 'https://pi.pardot.com/',
			),
			array(
				'host'        => 'www.govconwire.com',
				'type'        => 'referral',
				'name'        => 'GovCon Wire',
				'primary_url' => 'https://www.govconwire.com/',
			),
			array(
				'host'        => 'daluscapital.com',
				'type'        => 'referral',
				'name'        => 'Dalus Capital',
				'primary_url' => 'https://daluscapital.com/',
			),
			array(
				'host'        => 'en.wikipedia.org',
				'type'        => 'referral',
				'name'        => 'Wikipedia',
				'primary_url' => 'https://en.wikipedia.org/',
			),
			array(
				'host'        => 'cstheory.com',
				'type'        => 'referral',
				'name'        => 'Theoretical Computer Science',
				'primary_url' => 'https://cstheory.com/',
			),
			array(
				'host'        => 'portaldohost.com.br',
				'type'        => 'referral',
				'name'        => 'Portal do Host',
				'primary_url' => 'https://portaldohost.com.br/',
			),
			array(
				'host'        => 'alexamari.com',
				'type'        => 'referral',
				'name'        => 'Alex Amari',
				'primary_url' => 'https://alexamari.com/',
			),
			array(
				'host'        => 'www.marinelink.com',
				'type'        => 'referral',
				'name'        => 'MarineLink',
				'primary_url' => 'https://www.marinelink.com/',
			),
			array(
				'host'        => 'www.streetinsider.com',
				'type'        => 'referral',
				'name'        => 'StreetInsider.com',
				'primary_url' => 'https://www.streetinsider.com/',
			),
			array(
				'host'        => 'danielelizalde.com',
				'type'        => 'referral',
				'name'        => 'Daniel Elizalde',
				'primary_url' => 'https://danielelizalde.com/',
			),
			array(
				'host'        => 'www.darkreading.com',
				'type'        => 'referral',
				'name'        => 'Dark Reading',
				'primary_url' => 'https://www.darkreading.com/',
			),
			array(
				'host'        => 'go.pardot.com',
				'type'        => 'referral',
				'name'        => 'Pardot',
				'primary_url' => 'https://pi.pardot.com/',
			),
			array(
				'host'        => 'preview.pardot.com',
				'type'        => 'referral',
				'name'        => 'Pardot',
				'primary_url' => 'https://pi.pardot.com/',
			),
			array(
				'host'        => 'www.builtinaustin.com',
				'type'        => 'referral',
				'name'        => 'Built In Austin',
				'primary_url' => 'https://www.builtinaustin.com/',
			),
			array(
				'host'        => 'opendatascience.com',
				'type'        => 'referral',
				'name'        => 'Open Data Science',
				'primary_url' => 'https://opendatascience.com/',
			),
			array(
				'host'        => 'thetechtribune.com',
				'type'        => 'referral',
				'name'        => 'The Tech Tribune',
				'primary_url' => 'http://thetechtribune.com/',
			),
			array(
				'host'        => 'oneworldidentity.com',
				'type'        => 'referral',
				'name'        => 'One World Identity',
				'primary_url' => 'https://oneworldidentity.com/',
			),
			array(
				'host'        => 'www.canzmarketing.com',
				'type'        => 'referral',
				'name'        => 'Canz Marketing',
				'primary_url' => 'https://www.canzmarketing.com/',
			),

			// Edge cases.
			array(
				'host'        => 'PANTHEON_STRIPPED',
				'type'        => 'self-referral',
				'name'        => 'Self-referral',
			),
		);
	}
}
